name: Dependency Check no Backend

on:
  push:
    paths:
      - "PayWiseBackend/PayWiseBackend.csproj"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "30 10 * * *"

jobs:
  dependency-check:
    runs-on: windows-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cachear Arquivos NVD
        uses: actions/cache@v4
        id: cache-nvd
        with:
          save-always: true
          path: |
            dependency-check
          key: nvd-owasp123-dpcheck-mxm
          restore-keys: nvd-owasp123-dpcheck-mxm

      - name: Instalar Dependency-Check
        if: ${{ steps.cache-nvd.outputs.cache-hit != 'true' }}
        run: |
          Invoke-WebRequest -Uri "https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip" -OutFile "dependency-check.zip"
          Expand-Archive -Path "dependency-check.zip" -DestinationPath "."

      - name: Executar Dependency Check CLI Scan
        env:
          NOME_PROJETO: PayWiseBackend
          SCANEAR_CAMINHO: ./PayWiseBackend
          RESULTADO_CAMINHO: ./.cicd/dependency-check-report-backend
          ARQUIVO_SUPRESSAO: ./.cicd/dependency-check-config/suppression-backend.xml
        run: |
          .\dependency-check\bin\dependency-check.bat --project "${{ env.NOME_PROJETO }}" --scan "${{ env.SCANEAR_CAMINHO }}" --out "${{ env.RESULTADO_CAMINHO }}" --format "HTML" --format "JSON" --suppression "${{ env.ARQUIVO_SUPRESSAO }}" --nvdApiKey="${{ secrets.NVDAPIKEY }}"

      - name: Commitar Relatórios do Dependency Check
        run: |
          git fetch --all
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_USER_NAME }}"
          $env:GITHUB_EVENT_NAME = "${{ github.event_name }}"
          if ($env:GITHUB_EVENT_NAME -eq 'pull_request') {
            git checkout main
            git switch main } else {
            $branch_name = "${{ github.ref }}".replace('refs/heads/', '')
            git checkout $branch_name
            git switch $branch_name }
          git add ./.cicd/dependency-check-report-backend/*
          git commit -m "Add Dependency Check Reports" || echo "No changes to commit"
          git push origin HEAD --force
        shell: pwsh

      - name: Relatório de Vulnerabilidade
        id: checar_vulnerabilidades
        run: .\.cicd\scripts\run_dependencycheck.ps1 -CaminhoRelatorio "./.cicd/dependency-check-report-backend/dependency-check-report.json"

      - name: Falha na Build se Vulnerabilidades Altas ou Críticas Forem Encontradas
        if: ${{ steps.checar_vulnerabilidades.outputs.vulnerabilidade == 'true' }}
        run: .\.cicd\scripts\high_critical_vulnefound.ps1 -altoNivel "${{ steps.checar_vulnerabilidades.outputs.altoNivel }}" -criticoNivel "${{ steps.checar_vulnerabilidades.outputs.criticoNivel }}"
        shell: pwsh

      - name: Lidar com Vulnerabilidades de Baixo e Médio nível
        if: steps.checar_vulnerabilidades.outputs.vulnerabilidade != 'true' && steps.checar_vulnerabilidades.outputs.aviso == 'true'
        run: .\.cicd\scripts\low_medium_vulnefound.ps1 -baixoNivel "${{ steps.checar_vulnerabilidades.outputs.baixoNivel }}" -medioNivel "${{ steps.checar_vulnerabilidades.outputs.medioNivel }}"
        shell: pwsh
