name: Dependency Check no Frontend

on:
  push:
    paths:
      - "frontend/package.json"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "35 10 * * *"

env:
  NOME_PROJETO: PayWiseFrontend
  SCANEAR_CAMINHO: ./frontend
  RESULTADO_CAMINHO: ./.cicd/dependency-check-report-frontend
  ARQUIVO_SUPRESSAO: ./.cicd/dependency-check-config/suppression-frontend.xml
  LINK_SUPRESSAO: ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/.cicd/dependency-check-config/suppression-frontend.xml
  LINK_RELATORIOS: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}/.cicd/dependency-check-report-frontend
  USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  APIKEY: ${{ secrets.NVDAPIKEY }}

jobs:
  dependency-check-frontend:
    runs-on: windows-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cachear Arquivos NVD
        uses: actions/cache@v4
        id: cache-nvd
        with:
          save-always: true
          path: |
            dependency-check
          key: nvd-owasp123-dpcheck-mxm
          restore-keys: nvd-owasp123-dpcheck-mxm

      - name: Extrair o Nome da Branch
        shell: pwsh
        run: |
          $branch = "${{ github.head_ref }}".Replace("refs/heads/", "")
          if ($branch -eq "merge" -or $branch -eq "") { 
            $branch = "main" 
          }
          echo "branch=$branch" | Out-File -Append $env:GITHUB_OUTPUT
        id: extrair_branch

      - name: Instalar Dependency-Check
        if: ${{ steps.cache-nvd.outputs.cache-hit != 'true' }}
        run: |
          Invoke-WebRequest -Uri "https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip" -OutFile "dependency-check.zip"
          Expand-Archive -Path "dependency-check.zip" -DestinationPath "."

      - name: Executar Dependency Check CLI Scan
        run: |
          .\dependency-check\bin\dependency-check.bat --project "${{ env.NOME_PROJETO }}" --scan "${{ env.SCANEAR_CAMINHO }}" --out "${{ env.RESULTADO_CAMINHO }}" --format "HTML" --format "JSON" --suppression "${{ env.ARQUIVO_SUPRESSAO }}" --nvdApiKey="${{ env.APIKEY }}"

      - name: Commitar Relatórios do Dependency Check
        run: |
          echo "${{env.RESULTADO_CAMINHO}}"
          git fetch --all
          git config --local user.email "${{ env.USER_EMAIL }}"
          git config --local user.name "gustavoscarl"
          $env:GITHUB_EVENT_NAME = "${{ github.event_name }}"
          if ($env:GITHUB_EVENT_NAME -eq 'pull_request') {
            git checkout main
            git switch main } else {
            $branch_name = "${{ github.ref }}".replace('refs/heads/', '')
            git checkout $branch_name
            git switch $branch_name }
          git add "${{env.RESULTADO_CAMINHO}}/*"
          git commit -m "Adicionando Relatorios

          skip-checks: true"
          git push origin HEAD --force
        shell: pwsh

      - name: Relatório de Vulnerabilidade
        id: checar_vulnerabilidades
        run: .\.cicd\scripts\run_dependencycheck.ps1 -CaminhoRelatorio "${{env.RESULTADO_CAMINHO}}/dependency-check-report.json" -linkRelatorio "${{ env.RESULTADO_CAMINHO }}"

      - name: Falha na Build se Vulnerabilidades Altas ou Críticas Forem Encontradas
        if: ${{ steps.checar_vulnerabilidades.outputs.vulnerabilidade == 'true' }}
        run: .\.cicd\scripts\high_critical_vulnefound.ps1 -altoNivel "${{ steps.checar_vulnerabilidades.outputs.altoNivel }}" -criticoNivel "${{ steps.checar_vulnerabilidades.outputs.criticoNivel }}" -linkSupressao "${{ env.LINK_SUPRESSAO }}" -linkRelatorio "${{ env.LINK_RELATORIOS}}"
        shell: pwsh

      - name: Lidar com Vulnerabilidades de Baixo e Médio nível
        if: steps.checar_vulnerabilidades.outputs.vulnerabilidade != 'true' && steps.checar_vulnerabilidades.outputs.aviso == 'true'
        run: .\.cicd\scripts\low_medium_vulnefound.ps1 -baixoNivel "${{ steps.checar_vulnerabilidades.outputs.baixoNivel }}" -medioNivel "${{ steps.checar_vulnerabilidades.outputs.medioNivel }}" -linkSupressao "${{ env.LINK_SUPRESSAO}}" -linkRelatorio "${{ env.LINK_RELATORIOS }}"
        shell: pwsh
