name: Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Download Dependency-Check
      run: |
        Invoke-WebRequest -Uri "https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip" -OutFile "dependency-check.zip"
        Expand-Archive -Path "dependency-check.zip" -DestinationPath "."
    
    - name: Run Dependency-Check
      run: |
        .\dependency-check\dependency-check\bin\dependency-check.bat --project "MyProject" --scan "./" --out "./dependency-check-report" --format "HTML" --nvdApiKey "d2bb331f-4cad-45a5-90bb-3fe4e28e33f2"

    - name: Check for Vulnerabilities
      id: check_vulnerabilities
      run: |
        if ((Select-String -Path "./dependency-check-report/dependency-check-report.html" -Pattern "No dependencies were identified that have known vulnerabilities").Count -eq 0) {
          echo "::set-output name=vulnerable::true"
        } else {
          echo "::set-output name=vulnerable::false"
        }

    - name: Fail if vulnerabilities found
      if: steps.check_vulnerabilities.outputs.vulnerable == 'true'
      run: |
        echo "Vulnerabilities found, failing the build"
        exit 1
