name: Dependency Check no Backend

on:
  push:
    paths:
      - "PayWiseBackend/PayWiseBackend.csproj"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "30 10 * * *"

env:
  NOME_PROJETO: PayWiseBackend
  SCANEAR_CAMINHO: ./PayWiseBackend
  RESULTADO_CAMINHO: ./.cicd/dependency-check-report-backend
  ARQUIVO_SUPRESSAO: ./.cicd/dependency-check-config/suppression-backend.xml
  LINK_SUPRESSAO: ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/.cicd/dependency-check-config/suppression-frontend.xml
  USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  APIKEY: ${{ secrets.NVDAPIKEY }}

jobs:
  dependency-check-backend:
    runs-on: windows-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cachear Arquivos NVD
        uses: actions/cache@v4
        id: cache-nvd
        with:
          save-always: true
          path: |
            dependency-check
          key: nvd-owasp123-dpcheck-mxm
          restore-keys: nvd-owasp123-dpcheck-mxm

      - name: Extrair o Nome da Branch
        shell: pwsh
        run: |
          $branch = "${{ github.head_ref }}".Replace("refs/heads/", "")
          if ($branch -eq "merge" -or $branch -eq "") { 
            $branch = "main" 
          }
          echo "branch=$branch" | Out-File -Append $env:GITHUB_OUTPUT
        id: extrair_branch

      - name: Instalar Dependency-Check
        if: ${{ steps.cache-nvd.outputs.cache-hit != 'true' }}
        run: |
          Invoke-WebRequest -Uri "https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip" -OutFile "dependency-check.zip"
          Expand-Archive -Path "dependency-check.zip" -DestinationPath "."

      - name: Executar Dependency Check CLI Scan
        run: |
          .\dependency-check\bin\dependency-check.bat --project "${{ env.NOME_PROJETO }}" --scan "${{ env.SCANEAR_CAMINHO }}" --out "${{ env.RESULTADO_CAMINHO }}" --format "HTML" --format "JSON" --suppression "${{ env.ARQUIVO_SUPRESSAO }}" --nvdApiKey="${{ env.APIKEY }}"

      - name: Salvar Arquivos de Relatório
        uses: actions/upload-artifact@v4
        id: relatorios-artifact
        with:
          name: code-coverage-report
          path: ${{env.RESULTADO_CAMINHO}}/*

      - name: Relatório de Vulnerabilidade
        id: checar_vulnerabilidades
        run: .\.cicd\scripts\run_dependencycheck.ps1 -CaminhoRelatorio "${{env.RESULTADO_CAMINHO}}/dependency-check-report.json" -linkArtifact "${{ steps.relatorios-artifact.outputs.artifact-url }}"

      - name: Falha na Build se Vulnerabilidades Altas ou Críticas Forem Encontradas
        if: ${{ steps.checar_vulnerabilidades.outputs.vulnerabilidade == 'true' }}
        run: .\.cicd\scripts\high_critical_vulnefound.ps1 -altoNivel "${{ steps.checar_vulnerabilidades.outputs.altoNivel }}" -criticoNivel "${{ steps.checar_vulnerabilidades.outputs.criticoNivel }}" -linkArtifact "${{ steps.relatorios-artifact.outputs.artifact-url }}"
        shell: pwsh

      - name: Lidar com Vulnerabilidades de Baixo e Médio nível
        if: steps.checar_vulnerabilidades.outputs.vulnerabilidade != 'true' && steps.checar_vulnerabilidades.outputs.aviso == 'true'
        run: .\.cicd\scripts\low_medium_vulnefound.ps1 -baixoNivel "${{ steps.checar_vulnerabilidades.outputs.baixoNivel }}" -medioNivel "${{ steps.checar_vulnerabilidades.outputs.medioNivel }}" -linkArtifact "${{ steps.relatorios-artifact.outputs.artifact-url }}"
        shell: pwsh
